name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_to_aws:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/fedora/code/howlctiy/howlcity-marketplace-storefront
            git pull && yarn 
            yarn build
            pm2 restart all